apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: {{ .Values.appName }}
        image: saurabhkr952/counter-demo-app:24
        imagePullPolicy: Always
        ports:
        - containerPort: 9099

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}"
  namespace: {{ .Values.namepace }}
spec:
  selector:
    app: {{ .Values.appName }}                           # put labels from deployment
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 9099

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}"
  namespace: {{ .Values.namepace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-portfolio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}-{{ .Values.env }}"            # put name from service
            port:
              number: 31000